networks:
  default:
    name: trip_scraper_default  # Custom name for the default network

services:
  scraper:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/trip_scraper
    depends_on:
      - db
    command: scrapy crawl city_hotels
    networks:
      - default

  db:
    image: postgres:latest
    container_name: postgres_container_trip_scraper
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trip_scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default

volumes:
  postgres_data:
  pgadmin_data:
